"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { SendHorizontal, Sparkles, Wand2 } from "lucide-react";
import ChatMessage, { type ChatMessageType } from "./ChatMessage";
import MarkdownRenderer from "./MarkdownRenderer";
import Card from "../ui/Card";
import { generateImages, getResearch, type GeneratedImage, type ResearchResult } from "../../lib/mcpClient";

const baseWelcome: ChatMessageType = {
  id: "welcome",
  role: "assistant",
  content:
    "Welcome to your AI content studio. Describe the campaign you want and I will build the research, strategy, and visuals."
};

export default function Chat() {
  const [messages, setMessages] = useState<ChatMessageType[]>([baseWelcome]);
  const [input, setInput] = useState("");
  const [isThinking, setIsThinking] = useState(false);
  const [research, setResearch] = useState<ResearchResult[]>([]);
  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [report, setReport] = useState<string | null>(null);

  const buildTableMarkdown = (
    rows: ResearchResult[],
    previews: GeneratedImage[]
  ) => {
    if (rows.length === 0) return "";
    const header = "| Content Idea | Strategy | Image Preview |\n| --- | --- | --- |";
    const body = rows
      .map((row, index) => {
        const preview = previews[index] ? `Preview ${index + 1}` : "Pending";
        return `| ${row.contentIdea} | ${row.strategy} | ${preview} |`;
      })
      .join("\n");
    return `${header}\n${body}`;
  };

  const handleSubmit = async () => {
    if (!input.trim()) return;
    const prompt = input.trim();

    setMessages((prev) => [
      ...prev,
      { id: `${Date.now()}-user`, role: "user", content: prompt }
    ]);
    setInput("");
    setIsThinking(true);

    try {
      const researchResults = await getResearch(prompt);
      const imageResults = await generateImages(
        researchResults.map((item) => item.imagePrompt)
      );
      setResearch(researchResults);
      setImages(imageResults);

      const markdownTable = [
        "Here is the premium content plan based on your request:",
        "",
        buildTableMarkdown(researchResults, imageResults),
        "",
        "Image previews are ready below."
      ].join("\n");

      setMessages((prev) => [
        ...prev,
        {
          id: `${Date.now()}-assistant`,
          role: "assistant",
          content: markdownTable
        }
      ]);
    } catch (error) {
      const detail =
        error instanceof Error ? error.message : "Unknown MCP error";
      setMessages((prev) => [
        ...prev,
        {
          id: `${Date.now()}-assistant`,
          role: "assistant",
          content: [
            "I ran into an error reaching the MCP server.",
            "",
            `**Details:** ${detail}`,
            "",
            "Make sure the Python MCP server is running and CORS allows this origin."
          ].join("\n")
        }
      ]);
    } finally {
      setIsThinking(false);
    }
  };

  const handleGenerateReport = () => {
    if (research.length === 0) {
      setReport(
        "Start a campaign first, then generate the final report from the completed plan."
      );
      return;
    }

    const summary = [
      "# Final Campaign Report",
      "",
      "## Campaign Highlights",
      ...research.map(
        (item, index) =>
          `- **Idea ${index + 1}:** ${item.contentIdea}  \n  Strategy: ${item.strategy}`
      ),
      "",
      "## Visual Direction",
      ...images.map((img, index) => `- Preview ${index + 1}: ${img.alt}`),
      "",
      "_Generated by the AI Content Creator MCP pipeline._"
    ].join("\n");

    setReport(summary);
  };

  return (
    <div className="flex h-full flex-col">
      <div className="flex-1 space-y-5 overflow-auto px-6 pb-6 pt-4">
        {messages.map((message) => (
          <ChatMessage key={message.id} message={message} />
        ))}

        {isThinking ? (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="inline-flex items-center gap-2 rounded-full border border-slate-800 bg-slate-900/60 px-4 py-2 text-xs text-slate-300"
          >
            <Sparkles className="h-4 w-4 text-indigo-400" />
            Thinking and orchestrating MCP tools...
          </motion.div>
        ) : null}

        {images.length > 0 ? (
          <div className="grid gap-4 md:grid-cols-2">
            {images.map((image, index) => (
              <Card key={image.url} title={`Image Preview ${index + 1}`}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={image.url}
                  alt={image.alt}
                  className="h-44 w-full rounded-xl object-cover"
                />
                <p className="mt-3 text-xs text-slate-400">{image.alt}</p>
              </Card>
            ))}
          </div>
        ) : null}

        {report ? (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-indigo-500/30 bg-indigo-500/10 p-5 text-sm text-slate-100"
          >
            <div className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-indigo-300">
              Final Report
            </div>
            <MarkdownRenderer content={report} />
          </motion.div>
        ) : null}
      </div>

      <div className="border-t border-slate-800 bg-panel/80 px-6 py-4">
        <div className="flex flex-col gap-3">
          <div className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-3">
            <Wand2 className="h-4 w-4 text-indigo-300" />
            <input
              value={input}
              onChange={(event) => setInput(event.target.value)}
              placeholder="Ask for a content campaign, launch plan, or visual direction..."
              className="flex-1 bg-transparent text-sm text-slate-100 outline-none placeholder:text-slate-500"
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  void handleSubmit();
                }
              }}
            />
            <button
              onClick={() => void handleSubmit()}
              className="rounded-full bg-indigo-500 p-2 text-white transition hover:bg-indigo-400"
            >
              <SendHorizontal className="h-4 w-4" />
            </button>
          </div>
          <button
            onClick={handleGenerateReport}
            className="rounded-xl border border-indigo-400/40 bg-indigo-500/10 px-4 py-3 text-sm font-semibold text-indigo-100 transition hover:border-indigo-300/70"
          >
            Generate Final Report
          </button>
        </div>
      </div>
    </div>
  );
}
